### ISSUE TITLE
problem with library

### ISSUE THREAD

**Issue by amro153** [AdamBCo/ABCGooglePlacesAutocomplete#4]
when i open the app it crash 

GooglePlacesAutocomplete[4651:97640] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1024cb410'

**Comment by AdamBCo** [comment]
Did your replace the Google API key with the appropriate access token?

@amro153 

 When setting the API Key, you need to use the "Key for Browser Applications" not the "Key for iOS Applications".

Please let me know if this works

Thanks,

Adam

**Comment by LarryBrian** [comment]
@AdamBCo  I just got it working, thanks for updating the code. Guys be sure to not ONLY use the "API Key for Browser" BUT you also have to ENABLE "Google Places API for Web Service". I did not get it working until I did both of these things on the Google Developer Console!
