### ISSUE TITLE
pre-populate

### ISSUE THREAD

**Issue by daver234** [AdamBCo/ABCGooglePlacesAutocomplete#5]
Do you know of a way that the table view can be prepopulated when it comes up?  I want to be able for  a user to select "current location" as the address or have home and work as another two options.  For my app, the user is setting a start and end address for a drive.  Often they are using home and work and it would be better if it showed at the top of the list before typing begins and they can just select it. Or just select where I am now.  

Thanks,
Dave

**Comment by WadeSellers** [comment]
I just read this and am suggesting a way to make this work...  You could gather these pieces of info from them in the beginning of them using the app, store them in CoreData or NSUserDefaults locally if you like, then append them to the array at index 0 and 1 appropriately that the tableview is being populated from. Then what would would happen is your "home" and "work" locations would appear in the top 2 cells of the tableview and the search results from Google would populate under them as they would be in array indexes 3,4....

**Comment by AdamBCo** [comment]
@daver234 I apologize about the reply. In regards to your quest, the best for a "Home" and "Work" cell is to create a couple of static cells that refer to locations persisted in NSUserDefaults, Core Data, Realm, etc. A good example of this solution is the "Current Location" cell I have created in [Pixifly](https://itunes.apple.com/app/id830054948). The only additional fictionality you will need to provide is a way for users to identify that the address they are typing in, is indeed their "Work" or "Home" address. If you have any other questions, please don't hesitate to ask. Thanks for using the ABCGooglePlacesAutocomplete library.
